Asynchronous RGET implementation.
vbRGet() now spawns a goroutine so its treap visiting/iteration will
now be asynchronous.  A slow client requesting an RGET will no longer
block the vbucket's service() loop, allowing the vbucket to service
other concurrent clients.

Because the vbucket.items is now an immutable, MVCC treap, the
vbRGet() will be traversing a stable snapshot, and concurrent
mutations won't affect it.

For testing, following Dustin's errWriter approach, a slowWriter just
sleeps to pretend to be slow.  Before the vbRGet fix, TestSlowClient
would fail like...

    $ go test
    --- FAIL: TestSlowClient (0.05 seconds)
        ops_test.go:1164: Expected fast-client to be faster than slow-client.
        ops_test.go:1168: Expected slow-client to be slower than fast-client.
    FAIL
    exit status 1
    FAIL github.com/couchbaselabs/cbgb      0.569s